{{- if .Values.clusterrolebindingdecision }}
{{- if .Values.clusterrolebindingdecision.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digital-lending.fullname" . }}-crb
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "digital-lending.fullname" . }}-cr
subjects:
- kind: ServiceAccount
  name: {{ include "digital-lending.fullname" . }}-sa
  namespace: {{ include "digital-lending.namespace" . }}
{{- end }}
{{- end }}