{{- if .Values.clusterroledecision }}
{{- if .Values.clusterroledecision.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digital-lending.fullname" . }}-cr
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}