{{- if .Values.hpa.autoscaling.create }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "digital-lending.fullname" . }}-hpa
  namespace: {{ .Values.deployment.namespace | default (( include "digital-lending.namespace" . )) }}
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "digital-lending.fullname" . }}-app
  minReplicas: {{ .Values.hpa.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hpa.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.hpa.autoscaling.memory.averageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.autoscaling.memory.averageUtilization }}
    {{- end }}
    {{- if .Values.hpa.autoscaling.cpu.averageUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.autoscaling.cpu.averageUtilization }}
    {{- end }}
{{- end }}

