---
{{- if .Values.route.create }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "digital-lending.fullname" . }}-rt
  namespace: {{ .Values.deployment.namespace | default (( include "digital-lending.namespace" . )) }}
  labels:
{{ include "digital-lending.labels" . | indent 4 }}
  {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
  port:
    targetPort: {{ .Values.route.service.targetPort }}
{{- if .Values.route.tls.enabled }}
  tls:
{{- with .Values.route.tls }}
    termination: {{ .termination }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
    {{- with .key }}
    key: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .certificate }}
    certificate: |
{{ . | indent 6 }}
    {{- end }}
    {{- with .caCertificate }}
    caCertificate: |
{{ . | nindent 6 }}
    {{- end }}
    {{- with .destinationCACertificate }}
    destinationCACertificate: |
{{ . | nindent 6 }}
    {{- end }}
{{- end}}
{{- end }}
  to:
    kind: Service
    name:  {{ include "digital-lending.fullname" . }}-svc
    weight: {{ .Values.route.service.weight }}
{{- with .Values.route.alternateBackends }}
  alternateBackends:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
