{{- if .Values.scc }}
{{- if .Values.scc.create }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: {{ include "digital-lending.fullname" . }}-scc
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
allowPrivilegedContainer: true
allowHostNetwork: false
allowHostDirVolumePlugin: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowPrivilegeEscalation: true
runAsUser:
  type: MustRunAs
  uid: 200000001
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - projected
users:
  - system:serviceaccount:{{ include "digital-lending.namespace" . }}:{{ include "digital-lending.fullname" . }}-sa
{{- end }}
{{- end }}