{{- if .Values.secretpull.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-pull-sec
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
  namespace: {{ .Values.deployment.namespace | default (( include "digital-lending.namespace" . )) }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.secretpull.vault }}
data:
  .dockerconfigjson: {{ default "" .Values.secretpull.pull }}
type: {{ .Values.secretpull.type }}
{{- end }}

