{{- if .Values.secretdecision }}
{{- if .Values.secretdecision.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digital-lending.fullname" . }}-credentials
  namespace: {{ .Values.deployment.namespace | default (( include "digital-lending.namespace" . )) }}
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.secretdecision.vault }}
data:
  decision.password: {{ default "" .Values.secretdecision.decision }}
type: {{ .Values.secretdecision.type }}
{{- end }}
{{- end }}