{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "digital-lending.fullname" . }}-svc
  namespace: {{ .Values.deployment.namespace | default (( include "digital-lending.namespace" . )) }}
  labels:
    {{- include "digital-lending.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.nameport }}
  selector:
    {{- include "digital-lending.selectorLabels" . | nindent 4 }}
{{- end }}
